[universiteler]

ytu_variants = [
    "yıldız teknik üniversitesi",
    "yıldız teknik",
    "ytü",
    "yıldız teknik üniversitesi (ytü)",
    "yıldız teknik üniversitesi - ytü",
    "yildiz teknik universitesi",
    "yildiz teknik",
    "ytu",
    "yildiz teknik universitesi (ytu)",
    "yildiz teknik universitesi - ytu",
    "yildiz teknik universite",
    "yildiz teknik universitesı",
    "yildız teknik üniversıtesi",
    "yildız teknik ünıversitesi"
]

boun_variants = [
    "boğaziçi üniversitesi",
    "bogazici universitesi",
    "boğaziçi",
    "bogazici",
    "boun",
    "boğaziçi üniversitesi (boun)",
    "bogazici universitesi (boun)",
    "bogazici universtesi",
    "boğazıcı universitesi",
    "boğaziçi ünıversitesi",
    "bounn"
]

cerrahpasa_variants = [
    "istanbul üniversitesi-cerrahpaşa",
    "istanbul universitesi-cerrahpasa",
    "cerrahpaşa",
    "cerrahpasa",
    "iuc",
    "iüc",
    "iuc-cerrahpaşa",
    "iuc-cerrahpasa",
    "istanbul üniversitesi cerrahpaşa",
    "istanbul universitesi cerrahpasa",
    "cerrah pasa",
    "cerahpaşa",
    "cerahpasa"
]
